//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitness_verwaltung
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FitnessEntities : DbContext
    {
        public FitnessEntities()
            : base("name=FitnessEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_checkin> tbl_checkin { get; set; }
        public virtual DbSet<tbl_geraet> tbl_geraet { get; set; }
        public virtual DbSet<tbl_kursbuchung> tbl_kursbuchung { get; set; }
        public virtual DbSet<tbl_kurse> tbl_kurse { get; set; }
        public virtual DbSet<tbl_mitglieder> tbl_mitglieder { get; set; }
        public virtual DbSet<tbl_mitgliedschaft> tbl_mitgliedschaft { get; set; }
        public virtual DbSet<tbl_raum> tbl_raum { get; set; }
        public virtual DbSet<tbl_trainer> tbl_trainer { get; set; }
        public virtual DbSet<tbl_trainingsplan> tbl_trainingsplan { get; set; }
        public virtual DbSet<tbl_wartung> tbl_wartung { get; set; }
        public virtual DbSet<tbl_zahlung> tbl_zahlung { get; set; }
    }
}
