//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitness_verwaltung
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_kurse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_kurse()
        {
            this.tbl_kursbuchung = new HashSet<tbl_kursbuchung>();
        }
    
        public int PK_Kurs { get; set; }
        public string Titel { get; set; }
        public string Beschreibung { get; set; }
        public Nullable<System.DateTime> Startzeit { get; set; }
        public Nullable<System.DateTime> Endzeit { get; set; }
        public Nullable<int> FK_Trainer { get; set; }
        public Nullable<int> FK_Raum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_kursbuchung> tbl_kursbuchung { get; set; }
        public virtual tbl_raum tbl_raum { get; set; }
        public virtual tbl_trainer tbl_trainer { get; set; }
    }
}
