//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitness_verwaltung
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_checkin
    {
        public int PK_Checkin { get; set; }
        public Nullable<System.DateTime> Zeitpunkt { get; set; }
        public Nullable<int> FK_Mitglied { get; set; }
    
        public virtual tbl_mitglieder tbl_mitglieder { get; set; }
    }
}
