//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitness_verwaltung
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_wartung
    {
        public int PK_Wartung { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public string Bemerkung { get; set; }
        public Nullable<int> FK_Geraet { get; set; }
    
        public virtual tbl_geraet tbl_geraet { get; set; }
    }
}
