//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitness_verwaltung
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_geraet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_geraet()
        {
            this.tbl_wartung = new HashSet<tbl_wartung>();
        }
    
        public int PK_Geraet { get; set; }
        public string Bezeichnung { get; set; }
        public string Kategorie { get; set; }
        public Nullable<int> FK_Raum { get; set; }
    
        public virtual tbl_raum tbl_raum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_wartung> tbl_wartung { get; set; }
    }
}
