//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitness_verwaltung
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mitglieder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_mitglieder()
        {
            this.tbl_checkin = new HashSet<tbl_checkin>();
            this.tbl_kursbuchung = new HashSet<tbl_kursbuchung>();
            this.tbl_trainingsplan = new HashSet<tbl_trainingsplan>();
            this.tbl_zahlung = new HashSet<tbl_zahlung>();
        }
    
        public int PK_Mitglied { get; set; }
        public string Vorname { get; set; }
        public string Nachname { get; set; }
        public Nullable<System.DateTime> Geburtsdatum { get; set; }
        public Nullable<int> Telefon { get; set; }
        public string Adresse { get; set; }
        public Nullable<int> FK_Mitgliedschaft { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_checkin> tbl_checkin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_kursbuchung> tbl_kursbuchung { get; set; }
        public virtual tbl_mitgliedschaft tbl_mitgliedschaft { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_trainingsplan> tbl_trainingsplan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_zahlung> tbl_zahlung { get; set; }
    }
}
