//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitness_verwaltung
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mitgliedschaft
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_mitgliedschaft()
        {
            this.tbl_mitglieder = new HashSet<tbl_mitglieder>();
        }
    
        public int PK_Mitgliedschaft { get; set; }
        public string Bezeichnung { get; set; }
        public Nullable<decimal> Preis { get; set; }
        public Nullable<System.DateTime> Start_Zeit { get; set; }
        public Nullable<System.DateTime> End_Zeit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_mitglieder> tbl_mitglieder { get; set; }
    }
}
